#!/bin/bash

set -o pipefail
set -e
set -x

jupyter labextension install @jupyterlab/fasta-extension
jupyter labextension install jupyterlab-drawio
jupyter labextension install jupyterlab_tensorboard
